"""add_system_id_ai_configurations_and_upload_status

Revision ID: a1c63a884149
Revises: fb64d07d4bb2
Create Date: 2026-08-21 20:39:04.110094+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1c63a884149'
down_revision: str | None = 'fb64d07d4bb2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Define enum
uploadstatus_enum = sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='uploadstatus')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    uploadstatus_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('ai_configurations',
    sa.Column('system_id', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('retrieval_top_k', sa.Integer(), nullable=False),
    sa.Column('memory_enabled', sa.Boolean(), nullable=False),
    sa.Column('reasoning_effort', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_configurations_id'), 'ai_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_configurations_system_id'), 'ai_configurations', ['system_id'], unique=True)
    op.add_column('chat_histories', sa.Column('system_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_chat_histories_system_id'), 'chat_histories', ['system_id'], unique=False)
    op.add_column('memories', sa.Column('system_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_memories_system_id'), 'memories', ['system_id'], unique=False)
    op.add_column('uploads', sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'INDEXED', 'FAILED', name='uploadstatus'), nullable=False, server_default='UPLOADED'))
    op.create_index(op.f('ix_uploads_status'), 'uploads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uploads_status'), table_name='uploads')
    op.drop_column('uploads', 'status')
    op.execute("DROP TYPE IF EXISTS uploadstatus")
    op.drop_index(op.f('ix_memories_system_id'), table_name='memories')
    op.drop_column('memories', 'system_id')
    op.drop_index(op.f('ix_chat_histories_system_id'), table_name='chat_histories')
    op.drop_column('chat_histories', 'system_id')
    op.drop_index(op.f('ix_ai_configurations_system_id'), table_name='ai_configurations')
    op.drop_index(op.f('ix_ai_configurations_id'), table_name='ai_configurations')
    op.drop_table('ai_configurations')
    # ### end Alembic commands ###
