FROM node:20-alpine

WORKDIR /app

# Install dependencies needed for some node packages compile
RUN apk add --no-cache libc6-compat

# Copy package.json
COPY package.json ./

# Install packages
RUN npm install --legacy-peer-deps

# Expose port
EXPOSE 3000

# Start dev server
CMD ["npm", "run", "dev"]
